# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20160107_1755'),
        ('catalogue', '0008_auto_20160304_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='partner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
            preserve_default=False,
        ),
    ]
